apiVersion: v1
kind: Service
metadata:
  name: my-app-stage
  annotations:
    harness.io/stage-service: "true"
spec:
  type: ClusterIP
  selector:
    app: my-app
    version: <+infra.trafficShift.stageVersion>  # Points to the non-live version
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
