apiVersion: v1
kind: Service
metadata:
  name: my-app-primary
  annotations:
    harness.io/primary-service: "true"
spec:
  type: ClusterIP
  selector:
    app: my-app
    version: green  # Harness switches this between blue/green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
