apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  type: ClusterIP
  selector:
    app: my-app
    version: blue  # Initially pointing to BLUE
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
