apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  type: ClusterIP
  selector:
    app: my-app
    version: <+infra.trafficShift.version>  # Harness will switch this between blue/green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
